services:
  backend:
    build: ./backend
    ports:
      - "${API_PORT}:80"
    devices:
      - ${CAMERA_DIR}:/dev/video0
      - ${UART_DIR}:/dev/ttyAMA0
      - ${GPIO_DIR}:/dev/gpiomem
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "${DASHBOARD_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./frontend/src/:/usr/share/nginx/html/