services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./frontend/src/:/usr/share/nginx/html/